version: '3'

services:
###> doctrine/doctrine-bundle ###
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - /app/.idea #exclude from synchronization
    ports:
      - "18080:80"
      - "18081:81"
      - "18443:443"
  database:
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=rootsecret
    ports:
      - "127.0.0.1:33066:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local

